services:
  - type: web
    name: telegram-personal-manager-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main_simple
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false 